
development:
  clients:
    default:
      database: note_storage_development
      hosts:
        - localhost:27017


test:
  clients:
    default:
      database: note_storage_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
